# Generated by Django 2.2 on 2019-04-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_on',
            field=models.CharField(max_length=200),
        ),
    ]
